# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition = "2024"
name = "provider-integration-tests-capi"
version = "0.0.0"

[features]
integration = []

[build-dependencies]
cmake.workspace = true

[dev-dependencies]
libtest-mimic.workspace = true

[lints]
workspace = true

[[test]]
harness = false
name = "capi_gtest_runner"
path = "cpp/capi_gtest_runner.rs"
