// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for boot_handshake.
//!
//! 'Boot-time coordination region in GSRAM. Holds the HSM boot status word polled by Admin, and reserves space for the Admin ↔ HSM IPC queue indices and ring buffers (to be migrated from hardcoded constants in pal.rs).  Base address 0x6100_7000 is pinned to match V1 admin/hsm/mem-map layout and must not change (Admin hardcodes this offset in wait_for_hsm_run_state).  Reserved space (0x004..0x3FF) will hold: - IPC pair 0 RX_PI, RX_CI, TX_PI, TX_CI (4 × 4 B = 16 B) - IPC pair 0 RX_RING[2], TX_RING[2] (2 × 64 B = 128 B) - Additional pairs for FP/HSP if needed (~1 KB total)  Out of v1 scope (additive, not breaking): * IPC queue index/ring layout (currently hardcoded). * FP/HSP boot status words (if multi-core boot needs it).'

pub const BOOT_HANDSHAKE_BASE: u32 = 0x61007000;
pub const BOOT_STATUS_OFFSET: u32 = 0x00;

tock_registers::register_bitfields! [u32,
    /// 'HSM boot phase indicator. Written by HSM firmware to signal progress through the boot sequence. Polled by Admin firmware to gate post-handshake operations (host IO enable, NormalBoot to FP cores).  Values correspond to IoProcessorBootState enum discriminants: 0 = NotStarted (initial/reset state) 1 = Done       (PAL init complete, handshake ready) 2 = Run        (handshake complete, deferred init done)  Admin's `wait_for_hsm_run_state` blocks until this field reads Run (2), with a timeout of Tcon::tsc_freq_hz() / 2 cycles (~0.5s if TSC runs at expected frequency, or near-zero if TSC is misconfigured).  IMPORTANT: This field is volatile; both HSM write and Admin read must use volatile access to prevent compiler reordering or caching.'
    pub BOOT_STATUS [
        /// 'Boot status value (IoProcessorBootState discriminant: 0=NotStarted, 1=Done, 2=Run).'
        STATE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub BootHandshakeRegs {
            (0x0 => pub boot_status: crate::RW<u32, super::BOOT_STATUS::Register>),
            (0x4 => @END),
        }
    }
}
