// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for dummy_mem.
//!
//! 'Passive read-as-zero region (16 KB at 0xA0B0_0000), used as the constant zero source for GDMA-based buffer wiping.'

pub const DUMMY_MEM_BASE: u32 = 0xA0B00000;
pub const DUMMY_MEM_OFFSET: u32 = 0x00;
pub const DUMMY_MEM_COUNT: u32 = 1;
pub const DUMMY_MEM_STRIDE: u32 = 0x4000;
pub const DUMMY_MEM_SIZE: u32 = 0x4000;

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub DummyMemRegs {
            (0x0 => pub dummy_mem: [u8; 16384]),
            (0x4000 => @END),
        }
    }
}
