// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for hsm_dtcm_status.
//!
//! 'Per-core status and crashdump region in HSM (CP1) local DTCM. Holds the crashdump staging buffer and the liveliness heartbeat word polled by SP to detect hangs.  Base address 0x2003_F400 (local DTCM, as seen by HSM firmware) is pinned to match V1 mem-map/src/dtcm_hsm.rs layout: - CRASHDUMP_BASE @ 0x2003_F400 (V1 CRASHDUMP_BASE_OFFSET) - CORE_RUN_STATUS @ 0x2003_F800 (V1 CORE_RUN_STATUS_OFFSET)  SP accesses these via global addresses: - CRASHDUMP_BASE: 0x6063_F400 = CP_GLOBAL_ADDRESS(1, 0x2003_F400) - CORE_RUN_STATUS: 0x6063_F800 = CP_GLOBAL_ADDRESS(1, 0x2003_F800)  The reggen tool should emit a `*_BASE` constant of 0x6063_F400 (global address) so both HSM (via local alias) and SP (via DMB) can access. HSM firmware code will add the local base 0x2000_0000 offset if needed, or use direct local addressing.  Total region: 1028 B (0x404), laid out as: 0x000-0x3FF: CRASHDUMP_BASE (1024 B) 0x400-0x403: CORE_RUN_STATUS (4 B)'

pub const HSM_DTCM_STATUS_BASE: u32 = 0x2003F400;
pub const CORE_RUN_STATUS_OFFSET: u32 = 0x400;
pub const CRASHDUMP_BASE_OFFSET: u32 = 0x00;
pub const CRASHDUMP_BASE_COUNT: u32 = 1;
pub const CRASHDUMP_BASE_STRIDE: u32 = 0x400;
pub const CRASHDUMP_BASE_SIZE: u32 = 0x400;

tock_registers::register_bitfields! [u32,
    /// 'Per-core liveliness heartbeat. HSM firmware writes 1 to this word periodically (~250ms interval) to signal 'alive' status to the SP health monitor. SP reads this word via the global address (0x6063_F800), then zeroes it. If SP's next poll finds the word still zero, SP flags the core as hung and triggers crashdump collection.  Protocol: 1. HSM writes 1 every 100ms (Embassy task: core_liveliness) 2. SP reads value via DMB global address 3. If value != 0: SP writes 0, core is healthy 4. If value == 0: SP increments crash_count, prints 'Cores (status not updated): CP1', collects crashdump  V1 equivalent: HsmDtcmMemMap::core_run_status().set(1u32) called from hsm/src/handler.rs::on_timer_elapsed.  IMPORTANT: Both HSM write and SP read/write must use volatile access. HSM must write non-zero; SP zeroes after each poll.'
    pub CORE_RUN_STATUS [
        /// 'Liveliness indicator (HSM writes 1, SP reads then zeroes). Non-zero = alive.'
        ALIVE OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub HsmDtcmStatusRegs {
            (0x0 => pub crashdump_base: [u8; 1024]),
            (0x400 => pub core_run_status: crate::RW<u32, super::CORE_RUN_STATUS::Register>),
            (0x404 => @END),
        }
    }
}
