// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for part_entry_t.
//!
//! 'Per-partition lifecycle state, generation, 128-bit resource mask, provisioned ECC P-384 identity, and the enable-time establish-credential and session-encryption key pairs.'

pub const PART_ENTRY_T_BASE: u32 = 0x000BB000;
pub const STATE_OFFSET: u32 = 0x00;
pub const GENERATION_OFFSET: u32 = 0x04;
pub const RES_MASK_OFFSET: u32 = 0x08;
pub const ID_OFFSET: u32 = 0x18;
pub const ID_KEY_ID_OFFSET: u32 = 0x28;
pub const ID_PUB_KEY_OFFSET: u32 = 0x2C;
pub const EC_KEY_ID_OFFSET: u32 = 0x8C;
pub const EC_PUB_KEY_OFFSET: u32 = 0x90;
pub const SE_KEY_ID_OFFSET: u32 = 0xF0;
pub const SE_PUB_KEY_OFFSET: u32 = 0xF4;
pub const ENABLED_OFFSET: u32 = 0x154;
pub const RSVD_OFFSET: u32 = 0x154;

tock_registers::register_bitfields! [u32,
    /// 'Partition lifecycle state: 0=Unallocated, 1=Allocated, 2=Enabled, 3=Disabled.'
    pub STATE [
        STATE OFFSET(0) NUMBITS(8) [],
        RSVD OFFSET(8) NUMBITS(24) [],
    ],
    /// 'Monotonic generation counter, bumped whenever the partition is freed so previously issued key handles are rejected.'
    pub GENERATION [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'One 32-bit little-endian word of the 128-bit table-ownership mask. Bit i (global) selects key-vault table i.'
    pub RES_MASK [
        BITS OFFSET(0) NUMBITS(32) [],
    ],
    /// 'One 32-bit word of the 16-byte random partition identity.'
    pub ID [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Vault key id of the ECC P-384 identity private key (0 = not provisioned).'
    pub ID_KEY_ID [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'One 32-bit word of the 96-byte identity public key (X ‖ Y).'
    pub ID_PUB_KEY [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Vault key id of the ECC P-384 identity private key (0 = not provisioned).'
    pub EC_KEY_ID [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'One 32-bit word of the 96-byte identity public key (X ‖ Y).'
    pub EC_PUB_KEY [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Vault key id of the ECC P-384 identity private key (0 = not provisioned).'
    pub SE_KEY_ID [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'One 32-bit word of the 96-byte identity public key (X ‖ Y).'
    pub SE_PUB_KEY [
        VAL OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Reserved for future per-partition persistent fields.'
    pub RSVD [
        VAL OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub PartEntryTRegs {
            (0x0 => pub state: crate::RW<u32, super::STATE::Register>),
            (0x4 => pub generation: crate::RW<u32, super::GENERATION::Register>),
            (0x8 => pub res_mask: [crate::RW<u32, super::RES_MASK::Register>; 4]),
            (0x18 => pub id: [crate::RW<u32, super::ID::Register>; 4]),
            (0x28 => pub id_key_id: crate::RW<u32, super::ID_KEY_ID::Register>),
            (0x2c => pub id_pub_key: [crate::RW<u32, super::ID_PUB_KEY::Register>; 24]),
            (0x8c => pub ec_key_id: crate::RW<u32, super::EC_KEY_ID::Register>),
            (0x90 => pub ec_pub_key: [crate::RW<u32, super::EC_PUB_KEY::Register>; 24]),
            (0xf0 => pub se_key_id: crate::RW<u32, super::SE_KEY_ID::Register>),
            (0xf4 => pub se_pub_key: [crate::RW<u32, super::SE_PUB_KEY::Register>; 24]),
            (0x154 => pub rsvd: [crate::RW<u32, super::RSVD::Register>; 43]),
            (0x200 => @END),
        }
    }
}
