// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for sys_mbx.
//!
//! 'HSM-to-SP system mailbox (Mailbox0). The firmware sets S2H_MBX_INSTS.ERR_BIT to enter the FIPS error state.'

pub const SYS_MBX_BASE: u32 = 0xB0000000;
pub const S2H_MBX_CTRL_OFFSET: u32 = 0x00;
pub const S2H_MBX_INSTS_OFFSET: u32 = 0x04;
pub const S2H_MBX_FIFO_PUSH_OFFSET: u32 = 0x08;
pub const S2H_MBX_FIFO_POP_OFFSET: u32 = 0x0C;
pub const H2S_MBX_CTRL_OFFSET: u32 = 0x10;
pub const H2S_MBX_INSTS_OFFSET: u32 = 0x14;
pub const H2S_MBX_FIFO_PUSH_OFFSET: u32 = 0x18;
pub const H2S_MBX_FIFO_POP_OFFSET: u32 = 0x1C;

tock_registers::register_bitfields! [u32,
    /// 'System-to-HSP mailbox interrupt enables. Read-only from this core.'
    pub S2H_MBX_CTRL [
        /// 'FIFO full interrupt enable.'
        FIFO_FULL_INT_EN OFFSET(0) NUMBITS(1) [],
        /// 'FIFO not-empty interrupt enable.'
        FIFO_NEMPTY_INT_EN OFFSET(1) NUMBITS(1) [],
        /// 'FIFO valid interrupt enable.'
        FIFO_VALID_INT_EN OFFSET(2) NUMBITS(1) [],
        /// 'Error interrupt enable.'
        ERR_INT_EN OFFSET(3) NUMBITS(1) [],
    ],
    /// 'System-to-HSP mailbox interrupt status. Writing 1 to ERR_BIT raises the error interrupt to the SP.'
    pub S2H_MBX_INSTS [
        /// 'FIFO full status.'
        FIFO_FULL_INSTS OFFSET(0) NUMBITS(1) [],
        /// 'FIFO not-empty status.'
        FIFO_NEMPTY_INSTS OFFSET(1) NUMBITS(1) [],
        /// 'Write 1 to mark the FIFO data valid.'
        FIFO_VALID OFFSET(2) NUMBITS(1) [],
        /// 'Write 1 to raise the error interrupt to the SP.'
        ERR_BIT OFFSET(3) NUMBITS(1) [],
        /// 'Number of entries in the FIFO.'
        FIFO_CNT OFFSET(8) NUMBITS(8) [],
    ],
    /// 'Writing pushes a word into the system-to-HSP FIFO.'
    pub S2H_MBX_FIFO_PUSH [
        FIFO_DATA_PUSH OFFSET(0) NUMBITS(32) [],
    ],
    /// 'The word at the system-to-HSP FIFO output.'
    pub S2H_MBX_FIFO_POP [
        FIFO_DATA_POP OFFSET(0) NUMBITS(32) [],
    ],
    /// 'HSP-to-system mailbox interrupt enables.'
    pub H2S_MBX_CTRL [
        /// 'FIFO full interrupt enable.'
        FIFO_FULL_INT_EN OFFSET(0) NUMBITS(1) [],
        /// 'FIFO not-empty interrupt enable.'
        FIFO_NEMPTY_INT_EN OFFSET(1) NUMBITS(1) [],
        /// 'FIFO valid interrupt enable.'
        FIFO_VALID_INT_EN OFFSET(2) NUMBITS(1) [],
        /// 'Error interrupt enable.'
        ERR_INT_EN OFFSET(3) NUMBITS(1) [],
    ],
    /// 'HSP-to-system mailbox interrupt status.'
    pub H2S_MBX_INSTS [
        /// 'FIFO full status.'
        FIFO_FULL_INSTS OFFSET(0) NUMBITS(1) [],
        /// 'FIFO not-empty status.'
        FIFO_NEMPTY_INSTS OFFSET(1) NUMBITS(1) [],
        /// 'FIFO valid.'
        FIFO_VALID OFFSET(2) NUMBITS(1) [],
        /// 'Error bit.'
        ERR_BIT OFFSET(3) NUMBITS(1) [],
        /// 'Number of entries in the FIFO.'
        FIFO_CNT OFFSET(8) NUMBITS(8) [],
    ],
    /// 'The HSP-to-system FIFO input. Read-only from this core.'
    pub H2S_MBX_FIFO_PUSH [
        FIFO_DATA_PUSH OFFSET(0) NUMBITS(32) [],
    ],
    /// 'Reading pops a word from the HSP-to-system FIFO.'
    pub H2S_MBX_FIFO_POP [
        FIFO_DATA_POP OFFSET(0) NUMBITS(32) [],
    ]
];

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub SysMbxRegs {
            (0x0 => pub s2h_mbx_ctrl: crate::RO<u32, super::S2H_MBX_CTRL::Register>),
            (0x4 => pub s2h_mbx_insts: crate::RW<u32, super::S2H_MBX_INSTS::Register>),
            (0x8 => pub s2h_mbx_fifo_push: crate::RW<u32, super::S2H_MBX_FIFO_PUSH::Register>),
            (0xc => pub s2h_mbx_fifo_pop: crate::RO<u32, super::S2H_MBX_FIFO_POP::Register>),
            (0x10 => pub h2s_mbx_ctrl: crate::RW<u32, super::H2S_MBX_CTRL::Register>),
            (0x14 => pub h2s_mbx_insts: crate::RW<u32, super::H2S_MBX_INSTS::Register>),
            (0x18 => pub h2s_mbx_fifo_push: crate::RO<u32, super::H2S_MBX_FIFO_PUSH::Register>),
            (0x1c => pub h2s_mbx_fifo_pop: crate::RO<u32, super::H2S_MBX_FIFO_POP::Register>),
            (0x20 => @END),
        }
    }
}
