// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// AUTO-GENERATED by azihsm_reggen — do not edit.

//! Register definitions for zero.
//!
//! 'Passive read-as-zero AXI target (16 KB window at 0xA0B0_0000), used as the constant zero source for GDMA-based buffer wiping. Peripheral aperture, outside GSRAM.'

pub const ZERO_BASE: u32 = 0xA0B00000;
pub const ZERO_OFFSET: u32 = 0x00;
pub const ZERO_COUNT: u32 = 1;
pub const ZERO_STRIDE: u32 = 0x4000;
pub const ZERO_SIZE: u32 = 0x4000;

pub mod regs {
    //! MMIO register struct for firmware use.
    tock_registers::register_structs! {
        pub ZeroRegs {
            (0x0 => pub zero: [u8; 16384]),
            (0x4000 => @END),
        }
    }
}
