# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition = "2024"
name = "provider-tests"
version = "0.0.0"

[features]
integration = []

[build-dependencies]
cmake.workspace = true

[dev-dependencies]
libtest-mimic.workspace = true

[lints]
workspace = true

[[test]]
harness = false
name = "cpp"
path = "cpp/tests.rs"
