# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
[package]
edition = "2024"
name = "azihsm_sdk_fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
azihsm_ddi_emu = { path = "../ddi/emu" }
azihsm_ddi_interface = { path = "../ddi/interface" }
azihsm_ddi_tbor_codec = { path = "../ddi/tbor/codec" }
azihsm_ddi_tbor_test_harness = { features = [
  "emu",
], path = "../crates/tbor_test_harness" }
azihsm_ddi_tbor_types = { path = "../ddi/tbor/types" }
zerocopy = { version = "0.8.17" }

# dependencies for fuzzing
libfuzzer-sys = { features = ["arbitrary-derive"], version = "0.4" }

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_encoder"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_encoder.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_request_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_request_view.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_encoder"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_encoder.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_response_view"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_response_view.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_session_close"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_session_close.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_session_open_finish"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_session_open_finish.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_session_open_init"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_session_open_init.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_session_open_round_trip"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_session_open_round_trip.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_psk_change"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_psk_change.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_part_init"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_part_init.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_part_final"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_part_final.rs"
test = false

[[bin]]
bench = false
doc = false
name = "fuzz_tbor_part_info"
path = "fuzz_targets/ddi/tbor/fuzz_tbor_part_info.rs"
test = false
