// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/*
 * HSM-binding layer. The only translation unit that calls azihsm_* and the only
 * one that maps azihsm_status to CK_RV (azihsm_pkcs11_status.h). Two builds:
 *   - AZIHSM_WITH_HSM: binds the native C API against a real or simulated device.
 *   - otherwise: stubs that keep the framework loadable and the object/digest
 *     paths testable with no device present.
 */

#include "azihsm_pkcs11_hsm.h"
#include "azihsm_pkcs11_config.h"
#include "azihsm_pkcs11_internal.h"
#include "azihsm_pkcs11_status.h"

#include <stdlib.h>
#include <string.h>

#ifdef AZIHSM_WITH_HSM
#include "azihsm.h" /* generated by cbindgen from api/native during the build */

#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/provider.h>

/* azihsm_status values referenced by the lazy-provision decision. Spelled out
 * here (rather than via the enum) to keep the mapping table in azihsm_pkcs11_status.c the
 * single documented list. */
#define AZIHSM_OK 0
#define AZIHSM_CREDENTIALS_NOT_ESTABLISHED (-23)
#define AZIHSM_PARTITION_NOT_PROVISIONED (-25)
#define AZIHSM_PARTITION_ALREADY_PROVISIONED (-33)
#define AZIHSM_VAULT_APP_LIMIT_REACHED (-34)
#define AZIHSM_BUFFER_TOO_SMALL (-4)
#define AZIHSM_INTERNAL_ERROR (-5)

int32_t azihsm_pkcs11_hsm_enumerate_slots(void)
{
    azihsm_handle list = 0;
    azihsm_status st = azihsm_part_get_list(&list);
    if (st != AZIHSM_OK)
    {
        AZIHSM_PKCS11_LOG("part_get_list failed: %d", (int)st);
        return -1;
    }

    uint32_t count = 0;
    st = azihsm_part_get_count(list, &count);
    if (st != AZIHSM_OK)
    {
        AZIHSM_PKCS11_LOG("part_get_count failed: %d", (int)st);
        azihsm_part_free_list(list);
        return -1;
    }
    if (count > AZIHSM_PKCS11_MAX_SLOTS)
    {
        count = AZIHSM_PKCS11_MAX_SLOTS;
    }

    CK_ULONG produced = 0;
    for (uint32_t i = 0; i < count; i++)
    {
        struct azihsm_part_info info;
        memset(&info, 0, sizeof(info));

        info.path.str = NULL; /* sizing pass: BUFFER_TOO_SMALL fills path.len */
        info.path.len = 0;
        st = azihsm_part_get_info(list, i, &info);
        if (st != AZIHSM_OK && st != AZIHSM_BUFFER_TOO_SMALL)
        {
            AZIHSM_PKCS11_LOG("part_get_info(%u) sizing failed: %d", i, (int)st);
            continue;
        }
        uint32_t path_elems = info.path.len ? info.path.len : 1; /* incl. NUL */
        azihsm_char *buf = (azihsm_char *)calloc(path_elems, sizeof(azihsm_char));
        if (buf == NULL)
        {
            continue;
        }
        info.path.str = buf;
        info.path.len = path_elems;
        st = azihsm_part_get_info(list, i, &info);
        if (st != AZIHSM_OK)
        {
            AZIHSM_PKCS11_LOG("part_get_info(%u) fill failed: %d", i, (int)st);
            free(buf);
            continue;
        }

        azihsm_pkcs11_slot_t *slot = &g_azihsm_pkcs11.slots[produced];
        slot->present = true;
        slot->token_initialized = true; /* a discovered partition is a token */
        snprintf(slot->device_path, sizeof(slot->device_path), "%s", (const char *)buf);
        slot->api_rev_major = (uint16_t)info.api_rev_max.major;
        slot->api_rev_minor = (uint16_t)info.api_rev_max.minor;
        snprintf(slot->label, sizeof(slot->label), "AZIHSM partition %u", i);
        snprintf(slot->serial, sizeof(slot->serial), "AZIHSM%06u", i);
        free(buf);
        produced++;
    }

    azihsm_part_free_list(list);
    AZIHSM_PKCS11_LOG("enumerated %lu AZIHSM partition(s)", (unsigned long)produced);
    return (int32_t)produced;
}

/* Build the fixed-size AZIHSM credential from the configured id plus either the
 * caller's C_Login PIN or, when none was given, the configured default PIN. */
static void make_creds(
    struct azihsm_credentials *creds,
    const azihsm_pkcs11_config *cfg,
    const CK_UTF8CHAR *pin,
    CK_ULONG pin_len
)
{
    memset(creds, 0, sizeof(*creds));
    memcpy(creds->id, cfg->id, sizeof(creds->id));
    if (pin != NULL && pin_len > 0)
    {
        /* PIN-shape mapping: the PKCS#11 PIN (length already range-checked
         * against the advertised 16-byte max in C_Login) is copied into the
         * fixed 16-byte AZIHSM pin. A stable derivation (e.g. hash-to-16) is a
         * follow-up once the shape is agreed; the min() stays as a defensive
         * bound. */
        size_t n = pin_len < sizeof(creds->pin) ? (size_t)pin_len : sizeof(creds->pin);
        memcpy(creds->pin, pin, n);
    }
    else
    {
        memcpy(creds->pin, cfg->default_pin, sizeof(creds->pin));
    }
}

/*
 * Endorse the partition's PID public key with a caller POTA. The signature is
 * computed at runtime because the (simulated) partition key is regenerated per
 * device incarnation and cannot be precomputed: sign 0x04||x||y of the PID key
 * with ECDSA-SHA384 under a fresh P-384 key and return raw r||s (96 bytes) plus
 * that key's SPKI. Any self-consistent P-384 pair works — the device only
 * verifies the signature is consistent over the partition key, there is no
 * trust anchor to satisfy.
 *
 * Runs in a private OSSL_LIB_CTX with the default provider explicitly loaded:
 * the SDK runs its own crypto in a private libctx and leaves the process-global
 * default without a usable provider, so signing on the global context faults.
 */
static bool build_pota(
    const unsigned char *pid_spki,
    uint32_t pid_spki_len,
    unsigned char sig[96],
    unsigned char *pub,
    size_t *pub_len
)
{
    bool ok = false;
    OSSL_LIB_CTX *libctx = NULL;
    OSSL_PROVIDER *deflt = NULL;
    EVP_PKEY *sk = NULL;
    EVP_MD_CTX *md = NULL;
    unsigned char *der = NULL;
    ECDSA_SIG *es = NULL;

    /* M = the P-384 uncompressed point (0x04||x||y) = the trailing 97 bytes of
     * the SPKI DER. Sliced out rather than EVP-parsed for the libctx reason
     * above (EVP on a global-context key would fault). */
    const size_t POINT_LEN = 97;
    if (pid_spki_len < POINT_LEN)
    {
        goto cleanup;
    }
    const unsigned char *m = pid_spki + (pid_spki_len - POINT_LEN);
    if (m[0] != 0x04)
    {
        goto cleanup;
    }

    libctx = OSSL_LIB_CTX_new();
    if (libctx == NULL)
    {
        goto cleanup;
    }
    deflt = OSSL_PROVIDER_load(libctx, "default");
    if (deflt == NULL)
    {
        goto cleanup;
    }
    sk = EVP_PKEY_Q_keygen(libctx, NULL, "EC", "P-384");
    if (sk == NULL)
    {
        goto cleanup;
    }

    md = EVP_MD_CTX_new();
    if (md == NULL || EVP_DigestSignInit_ex(md, NULL, "SHA384", libctx, NULL, sk, NULL) != 1)
    {
        goto cleanup;
    }
    size_t der_len = 0;
    if (EVP_DigestSign(md, NULL, &der_len, m, POINT_LEN) != 1)
    {
        goto cleanup;
    }
    der = (unsigned char *)malloc(der_len);
    if (der == NULL || EVP_DigestSign(md, der, &der_len, m, POINT_LEN) != 1)
    {
        goto cleanup;
    }

    /* DER ECDSA sig -> raw r||s, 48 bytes each (the device requires 96). */
    const unsigned char *dp = der;
    es = d2i_ECDSA_SIG(NULL, &dp, (long)der_len);
    if (es == NULL)
    {
        goto cleanup;
    }
    const BIGNUM *r = NULL;
    const BIGNUM *s = NULL;
    ECDSA_SIG_get0(es, &r, &s);
    if (BN_bn2binpad(r, sig, 48) != 48 || BN_bn2binpad(s, sig + 48, 48) != 48)
    {
        goto cleanup;
    }

    int pl = i2d_PUBKEY(sk, NULL);
    if (pl <= 0 || (size_t)pl > *pub_len)
    {
        goto cleanup;
    }
    unsigned char *pp = pub;
    if (i2d_PUBKEY(sk, &pp) != pl)
    {
        goto cleanup;
    }
    *pub_len = (size_t)pl;
    ok = true;

cleanup:
    if (es != NULL)
    {
        ECDSA_SIG_free(es);
    }
    free(der);
    if (md != NULL)
    {
        EVP_MD_CTX_free(md);
    }
    if (sk != NULL)
    {
        EVP_PKEY_free(sk);
    }
    if (deflt != NULL)
    {
        OSSL_PROVIDER_unload(deflt);
    }
    if (libctx != NULL)
    {
        OSSL_LIB_CTX_free(libctx);
    }
    return ok;
}

/* Run the one-time provisioning ceremony on an already-open partition handle.
 * Returns the device's raw status: the caller decides which non-OK statuses
 * (e.g. a concurrent process winning the provisioning race) still allow the
 * login to proceed. */
static azihsm_status provision(azihsm_handle dev, const struct azihsm_credentials *creds)
{
    struct azihsm_part_prop prop = { AZIHSM_PART_PROP_ID_PART_PUB_KEY, NULL, 0 };
    azihsm_status st = azihsm_part_get_prop(dev, &prop);
    if (st != AZIHSM_OK && st != AZIHSM_BUFFER_TOO_SMALL)
    {
        return st;
    }
    unsigned char *pid = (unsigned char *)malloc(prop.len ? prop.len : 1);
    if (pid == NULL)
    {
        return AZIHSM_INTERNAL_ERROR;
    }
    prop.val = pid;
    st = azihsm_part_get_prop(dev, &prop);
    if (st != AZIHSM_OK)
    {
        free(pid);
        return st;
    }

    unsigned char sig[96];
    unsigned char pub[256];
    size_t pub_len = sizeof(pub);
    bool pota_ok = build_pota(pid, prop.len, sig, pub, &pub_len);
    free(pid);
    if (!pota_ok)
    {
        AZIHSM_PKCS11_LOG("POTA endorsement build failed");
        return AZIHSM_INTERNAL_ERROR;
    }

    azihsm_pkcs11_config cfg;
    azihsm_pkcs11_config_load(&cfg);
    struct azihsm_buffer obk_buf = { cfg.obk, sizeof(cfg.obk) };
    struct azihsm_owner_backup_key_config obk_cfg = { AZIHSM_OWNER_BACKUP_KEY_SOURCE_CALLER,
                                                      &obk_buf,
                                                      NULL };
    struct azihsm_buffer sig_buf = { sig, sizeof(sig) };
    struct azihsm_buffer pub_buf = { pub, (uint32_t)pub_len };
    struct azihsm_pota_endorsement_data pdata = { &sig_buf, &pub_buf };
    struct azihsm_pota_endorsement pota = { AZIHSM_POTA_ENDORSEMENT_SOURCE_CALLER, &pdata };

    return azihsm_part_init(dev, creds, NULL, NULL, &obk_cfg, &pota, NULL);
}

CK_RV azihsm_pkcs11_hsm_login(
    CK_SLOT_ID slot,
    const CK_UTF8CHAR *pin,
    CK_ULONG pin_len,
    uint32_t *out_session
)
{
    if (out_session == NULL)
    {
        return CKR_ARGUMENTS_BAD;
    }
    if (slot >= g_azihsm_pkcs11.slot_count)
    {
        return CKR_SLOT_ID_INVALID;
    }
    azihsm_pkcs11_slot_t *sl = &g_azihsm_pkcs11.slots[slot];

    /* Open the partition once per slot and reuse it across logins. */
    if (sl->hsm_dev == 0)
    {
        const char *path = sl->device_path;
        struct azihsm_str spath = { (azihsm_char *)path, (uint32_t)(strlen(path) + 1) };
        struct azihsm_api_rev rev = { sl->api_rev_major ? sl->api_rev_major : 1,
                                      sl->api_rev_minor };
        azihsm_handle dev = 0;
        azihsm_status st = azihsm_part_open(&spath, &dev, rev);
        if (st != AZIHSM_OK)
        {
            AZIHSM_PKCS11_LOG("part_open failed: %d", (int)st);
            return azihsm_pkcs11_ckr_from_azihsm((int)st);
        }
        sl->hsm_dev = dev;
    }

    struct azihsm_credentials creds;
    azihsm_pkcs11_config cfg;
    azihsm_pkcs11_config_load(&cfg);
    make_creds(&creds, &cfg, pin, pin_len);

    /* Login = OpenSession. Provisioning is a separate, one-shot-per-power-cycle
     * device operation; run it only if the device says it is not yet provisioned
     * (cold, or after a reset). */
    azihsm_handle sess = 0;
    azihsm_status st = azihsm_sess_open(sl->hsm_dev, &creds, NULL, &sess);
    if (st == AZIHSM_CREDENTIALS_NOT_ESTABLISHED || st == AZIHSM_PARTITION_NOT_PROVISIONED)
    {
        st = provision(sl->hsm_dev, &creds);
        /* ALREADY_PROVISIONED / VAULT_APP_LIMIT_REACHED mean a concurrent
         * process won the provisioning race between our sess_open probe and the
         * part_init; the SDK treats both as "credentials already established"
         * (api/lib/src/resiliency.rs, is_credentials_already_established). The
         * sess_open retry below verifies the credential either way and its
         * result is what the caller sees. */
        if (st != AZIHSM_OK && st != AZIHSM_PARTITION_ALREADY_PROVISIONED &&
            st != AZIHSM_VAULT_APP_LIMIT_REACHED)
        {
            AZIHSM_PKCS11_LOG("provision failed: %d", (int)st);
            return azihsm_pkcs11_ckr_from_azihsm((int)st);
        }
        st = azihsm_sess_open(sl->hsm_dev, &creds, NULL, &sess);
    }
    if (st != AZIHSM_OK)
    {
        AZIHSM_PKCS11_LOG("sess_open failed: %d", (int)st);
        return azihsm_pkcs11_ckr_from_azihsm((int)st);
    }
    *out_session = sess;
    AZIHSM_PKCS11_LOG("login ok (dev=%u sess=%u)", sl->hsm_dev, sess);
    return CKR_OK;
}

void azihsm_pkcs11_hsm_logout(uint32_t hsm_session)
{
    if (hsm_session != 0)
    {
        (void)azihsm_sess_close(hsm_session);
    }
}

void azihsm_pkcs11_hsm_close_all(void)
{
    for (CK_ULONG i = 0; i < g_azihsm_pkcs11.slot_count; i++)
    {
        if (g_azihsm_pkcs11.slots[i].hsm_dev != 0)
        {
            (void)azihsm_part_close(g_azihsm_pkcs11.slots[i].hsm_dev);
            g_azihsm_pkcs11.slots[i].hsm_dev = 0;
        }
    }
}

#else /* !AZIHSM_WITH_HSM ---------------------------------------------------- */

/* No device linked: one placeholder slot, and a login that "succeeds" with a
 * sentinel so the framework and object/digest paths stay exercisable. */

int32_t azihsm_pkcs11_hsm_enumerate_slots(void)
{
    azihsm_pkcs11_slot_t *slot = &g_azihsm_pkcs11.slots[0];
    slot->present = true;
    slot->token_initialized = true;
    snprintf(slot->device_path, sizeof(slot->device_path), "azihsm-placeholder-0");
    snprintf(slot->label, sizeof(slot->label), "AZIHSM (no device)");
    snprintf(slot->serial, sizeof(slot->serial), "AZIHSM000000");
    slot->api_rev_major = 1;
    slot->api_rev_minor = 0;
    return 1; /* slot count: the placeholder above */
}

CK_RV azihsm_pkcs11_hsm_login(
    CK_SLOT_ID slot,
    const CK_UTF8CHAR *pin,
    CK_ULONG pin_len,
    uint32_t *out_session
)
{
    (void)slot;
    (void)pin;
    (void)pin_len;
    if (out_session == NULL)
    {
        return CKR_ARGUMENTS_BAD;
    }
    *out_session = 0xFFFFFFFFu; /* sentinel: logged in, no device session */
    return CKR_OK;
}

void azihsm_pkcs11_hsm_logout(uint32_t hsm_session)
{
    (void)hsm_session;
}

void azihsm_pkcs11_hsm_close_all(void)
{
}

#endif /* AZIHSM_WITH_HSM */
