// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Per-key-kind request validation that produces an
//! [`HsmVaultKeyAttrs`] ready to hand to
//! [`HsmVault::vault_key_create`].
//!
//! Each `prepare_*` function combines two checks every key-creating
//! handler needs before it can store a key in the vault:
//!
//! 1. **Usage-bit policy** — translate the DDI `key_metadata`
//!    bitflags into a vault attribute set the requested key kind is
//!    allowed to carry.  Exactly one of the five usage groups must
//!    be set; per-kind rules then either accept or reject the chosen
//!    usage.  `local` is set from the caller (`true` for keys
//!    generated by the firmware, `false` for keys imported from the
//!    host via `RsaUnwrap`).
//!
//! 2. **Session/key_tag consistency** — a session-only key is
//!    anonymous (auto-deleted on `CloseSession`) and so cannot carry
//!    a host-supplied `key_tag` that would be used to look it up
//!    across sessions.
//!
//! Folding both checks into one call keeps the per-handler
//! pre-crypto fast path uniform — the handler runs `prepare_*`
//! before any expensive operation (RNG fill, ECDH, ECC keygen) so a
//! malformed request fails before we burn cycles.

use azihsm_fw_ddi_mbor_types::DdiTargetKeyMetadata;
use azihsm_fw_hsm_pal_traits::HsmEccCurve;
use azihsm_fw_hsm_pal_traits::HsmError;
use azihsm_fw_hsm_pal_traits::HsmResult;
use azihsm_fw_hsm_pal_traits::HsmVaultKeyAttrs;

/// Prepare vault attrs for an ECC private key.
///
/// ECC keys can sign / verify (matched pair) or derive (ECDH).
/// `encrypt_decrypt`, `unwrap`, and `wrap` are rejected with
/// [`HsmError::InvalidPermissions`].  `wrap` is folded into the
/// usage-count even though no curve currently allows it, so that
/// `sign+verify+wrap` is rejected as multi-usage rather than
/// silently treated as plain `sign+verify`.
///
/// The `curve` parameter is currently unused — all three NIST
/// curves accept the same usages — but kept in the signature so
/// future curve-specific tightening lands without a call-site
/// churn.
pub(crate) fn prepare_ecc(
    curve: HsmEccCurve,
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
    local: bool,
) -> HsmResult<HsmVaultKeyAttrs> {
    let _ = curve;
    validate_pairs(metadata)?;
    let mut attrs = HsmVaultKeyAttrs::new().with_local(local);

    let sign_verify = metadata.sign() && metadata.verify();
    let encrypt_decrypt = metadata.encrypt() && metadata.decrypt();
    let derive = metadata.derive();
    let unwrap = metadata.unwrap();
    let wrap = metadata.wrap();

    let usage_count = (sign_verify as u8)
        + (encrypt_decrypt as u8)
        + (derive as u8)
        + (unwrap as u8)
        + (wrap as u8);
    if usage_count != 1 {
        return Err(HsmError::InvalidPermissions);
    }

    if encrypt_decrypt || unwrap || wrap {
        return Err(HsmError::InvalidPermissions);
    }

    if sign_verify {
        attrs = attrs.with_sign(true).with_verify(true);
    }
    if derive {
        attrs = attrs.with_derive(true);
    }

    finalize(&mut attrs, metadata, key_tag)?;
    Ok(attrs)
}

/// Prepare vault attrs for a non-bulk AES key.
///
/// AES (non-bulk) keys can only carry `EncryptDecrypt`.  Any other
/// usage flag — sign, verify, derive, wrap, or unwrap — is rejected
/// with [`HsmError::InvalidPermissions`].
pub(crate) fn prepare_aes(
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
    local: bool,
) -> HsmResult<HsmVaultKeyAttrs> {
    validate_pairs(metadata)?;
    let mut attrs = HsmVaultKeyAttrs::new().with_local(local);

    let sign_verify = metadata.sign() && metadata.verify();
    let encrypt_decrypt = metadata.encrypt() && metadata.decrypt();
    let derive = metadata.derive();
    let wrap = metadata.wrap();
    let unwrap = metadata.unwrap();

    let usage_count = (sign_verify as u8)
        + (encrypt_decrypt as u8)
        + (derive as u8)
        + (wrap as u8)
        + (unwrap as u8);
    if usage_count != 1 {
        return Err(HsmError::InvalidPermissions);
    }

    if !encrypt_decrypt {
        return Err(HsmError::InvalidPermissions);
    }
    attrs = attrs.with_encrypt(true).with_decrypt(true);

    finalize(&mut attrs, metadata, key_tag)?;
    Ok(attrs)
}

/// Prepare vault attrs for an ECDH-derived shared secret.
///
/// Derived secrets are HKDF / KBKDF inputs, so the only valid usage
/// is `derive` (PKCS#11 `CKA_DERIVE`).  Any other usage is rejected
/// with [`HsmError::InvalidPermissions`].
pub(crate) fn prepare_ecdh_secret(
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
    local: bool,
) -> HsmResult<HsmVaultKeyAttrs> {
    validate_pairs(metadata)?;
    let mut attrs = HsmVaultKeyAttrs::new().with_local(local);

    let sign_verify = metadata.sign() && metadata.verify();
    let encrypt_decrypt = metadata.encrypt() && metadata.decrypt();
    let derive = metadata.derive();
    let wrap = metadata.wrap();
    let unwrap = metadata.unwrap();

    let usage_count = (sign_verify as u8)
        + (encrypt_decrypt as u8)
        + (derive as u8)
        + (wrap as u8)
        + (unwrap as u8);
    if usage_count != 1 {
        return Err(HsmError::InvalidPermissions);
    }

    if !derive {
        return Err(HsmError::InvalidPermissions);
    }
    attrs = attrs.with_derive(true);

    finalize(&mut attrs, metadata, key_tag)?;
    Ok(attrs)
}

/// Prepare vault attrs for an RSA private key.
///
/// RSA private keys can carry exactly one of `sign+verify`,
/// `encrypt+decrypt`, or `unwrap`; `derive` and `wrap` are not
/// valid usages for an RSA private key.
pub(crate) fn prepare_rsa(
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
    local: bool,
) -> HsmResult<HsmVaultKeyAttrs> {
    validate_pairs(metadata)?;
    let mut attrs = HsmVaultKeyAttrs::new().with_local(local);

    let sign_verify = metadata.sign() && metadata.verify();
    let encrypt_decrypt = metadata.encrypt() && metadata.decrypt();
    let derive = metadata.derive();
    let wrap = metadata.wrap();
    let unwrap = metadata.unwrap();

    let usage_count = (sign_verify as u8)
        + (encrypt_decrypt as u8)
        + (derive as u8)
        + (wrap as u8)
        + (unwrap as u8);
    if usage_count != 1 {
        return Err(HsmError::InvalidPermissions);
    }

    if derive || wrap {
        return Err(HsmError::InvalidPermissions);
    }

    if sign_verify {
        attrs = attrs.with_sign(true).with_verify(true);
    }
    if encrypt_decrypt {
        attrs = attrs.with_encrypt(true).with_decrypt(true);
    }
    if unwrap {
        attrs = attrs.with_unwrap(true);
    }

    finalize(&mut attrs, metadata, key_tag)?;
    Ok(attrs)
}

/// Prepare vault attrs for a derived variable-length HMAC key.
///
/// HMAC keys produced by HKDF / KBKDF can sign / verify MACs or act
/// as a key-derivation key (`derive`) for a further KDF.  Exactly one
/// of those two usage groups must be set; `encrypt_decrypt`, `wrap`,
/// and `unwrap` are rejected with [`HsmError::InvalidPermissions`].
pub(crate) fn prepare_var_hmac(
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
    local: bool,
) -> HsmResult<HsmVaultKeyAttrs> {
    validate_pairs(metadata)?;
    let mut attrs = HsmVaultKeyAttrs::new().with_local(local);

    let sign_verify = metadata.sign() && metadata.verify();
    let encrypt_decrypt = metadata.encrypt() && metadata.decrypt();
    let derive = metadata.derive();
    let wrap = metadata.wrap();
    let unwrap = metadata.unwrap();

    let usage_count = (sign_verify as u8)
        + (encrypt_decrypt as u8)
        + (derive as u8)
        + (wrap as u8)
        + (unwrap as u8);
    if usage_count != 1 {
        return Err(HsmError::InvalidPermissions);
    }

    if encrypt_decrypt || wrap || unwrap {
        return Err(HsmError::InvalidPermissions);
    }

    if sign_verify {
        attrs = attrs.with_sign(true).with_verify(true);
    }
    if derive {
        attrs = attrs.with_derive(true);
    }

    finalize(&mut attrs, metadata, key_tag)?;
    Ok(attrs)
}

/// Reject metadata where one half of a paired usage flag is set
/// without the other (`sign` without `verify`, or `encrypt`
/// without `decrypt`).  The host is supposed to encode these as
/// matched pairs; a half-set pair is either a malformed request
/// or an attempt to smuggle in a usage bit that would be silently
/// dropped by the `sign && verify` / `encrypt && decrypt` grouping
/// in the per-kind builders above.
fn validate_pairs(metadata: &DdiTargetKeyMetadata) -> HsmResult<()> {
    if metadata.sign() != metadata.verify() {
        return Err(HsmError::InvalidPermissions);
    }
    if metadata.encrypt() != metadata.decrypt() {
        return Err(HsmError::InvalidPermissions);
    }
    Ok(())
}

/// Apply the cross-cutting bits common to every `prepare_*` — set
/// the `session` flag from metadata and reject a session-only
/// request that also carries a host-supplied `key_tag` (session-only
/// keys are anonymous and not looked up across sessions).
fn finalize(
    attrs: &mut HsmVaultKeyAttrs,
    metadata: &DdiTargetKeyMetadata,
    key_tag: Option<u16>,
) -> HsmResult<()> {
    if metadata.session() {
        *attrs = attrs.with_session(true);
    }
    if attrs.session() && key_tag.is_some() {
        return Err(HsmError::InvalidArg);
    }
    Ok(())
}
