// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/*
 * HSM key binding (see azihsm_pkcs11_key.h). Two builds, mirroring azihsm_pkcs11_hsm.c:
 *   - AZIHSM_WITH_HSM: binds azihsm_key_* / azihsm_crypt_* against the device.
 *   - otherwise: stubs, so the framework and the entry-point validation paths
 *     stay testable with no device present.
 */

#include "azihsm_pkcs11_key.h"
#include "azihsm_pkcs11_internal.h"
#include "azihsm_pkcs11_status.h"

#include <stdlib.h>
#include <string.h>

#ifdef AZIHSM_WITH_HSM
#include "azihsm.h" /* generated by cbindgen from api/native during the build */

/* The IV buffer this file copies into the device CBC params must be exactly the
 * width AES_BLOCK_LEN promises to callers of azihsm_pkcs11_key_aes_cbc. */
_Static_assert(
    sizeof(((struct azihsm_algo_aes_cbc_params *)0)->iv) == AES_BLOCK_LEN,
    "device AES-CBC IV width must equal AES_BLOCK_LEN"
);

CK_RV azihsm_pkcs11_key_aes_generate(
    uint32_t hsm_session,
    uint32_t bit_len,
    CK_BYTE **out_blob,
    CK_ULONG *out_blob_len
)
{
    if ((out_blob == NULL) || (out_blob_len == NULL))
    {
        return CKR_ARGUMENTS_BAD;
    }
    *out_blob = NULL;
    *out_blob_len = 0;

    /*
     * SENSITIVE / EXTRACTABLE / LOCAL are deliberately absent: the SDK rejects
     * them as inputs (it sets them itself), which is why the template
     * normaliser in azihsm_pkcs11_crypt.c strips them before this call. SESSION is
     * always true — device residence is per-session by design here; the masked
     * blob below is what persists. ENCRYPT and DECRYPT are always both set:
     * the SDK refuses an AES key with only one of them (see the header note).
     */
    uint32_t class_secret = AZIHSM_KEY_CLASS_SECRET;
    uint32_t kind_aes = AZIHSM_KEY_KIND_AES;
    uint8_t yes = 1;
    struct azihsm_key_prop props[] = {
        { AZIHSM_KEY_PROP_ID_CLASS, &class_secret, sizeof(class_secret) },
        { AZIHSM_KEY_PROP_ID_KIND, &kind_aes, sizeof(kind_aes) },
        { AZIHSM_KEY_PROP_ID_BIT_LEN, &bit_len, sizeof(bit_len) },
        { AZIHSM_KEY_PROP_ID_SESSION, &yes, sizeof(yes) },
        { AZIHSM_KEY_PROP_ID_ENCRYPT, &yes, sizeof(yes) },
        { AZIHSM_KEY_PROP_ID_DECRYPT, &yes, sizeof(yes) },
    };
    struct azihsm_key_prop_list prop_list = { props, sizeof(props) / sizeof(props[0]) };
    struct azihsm_algo algo = { AZIHSM_ALGO_ID_AES_KEY_GEN, NULL, 0 };

    azihsm_handle key = 0;
    azihsm_status st = azihsm_key_gen(hsm_session, &algo, &prop_list, &key);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("key_gen(AES-%u) failed: %d", bit_len, (int)st);
        /* The only handle passed here is the device session: it going stale
         * means the recorded login no longer holds. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_USER_NOT_LOGGED_IN);
    }

    /* Read back the masked blob (two-call sizing), then drop the transient
     * device handle — the blob is the durable form of the key. */
    CK_RV rv = CKR_FUNCTION_FAILED;
    CK_BYTE *blob = NULL;
    struct azihsm_key_prop masked = { AZIHSM_KEY_PROP_ID_MASKED_KEY, NULL, 0 };
    st = azihsm_key_get_prop(key, &masked);
    if ((st != AZIHSM_STATUS_BUFFER_TOO_SMALL) || (masked.len == 0))
    {
        AZIHSM_PKCS11_LOG("masked-key sizing failed: %d", (int)st);
        rv = azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
        goto cleanup;
    }
    blob = (CK_BYTE *)malloc(masked.len);
    if (blob == NULL)
    {
        rv = CKR_HOST_MEMORY;
        goto cleanup;
    }
    masked.val = blob;
    st = azihsm_key_get_prop(key, &masked);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("masked-key readback failed: %d", (int)st);
        rv = azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
        goto cleanup;
    }

    *out_blob = blob;
    *out_blob_len = masked.len;
    blob = NULL; /* ownership moved to the caller */
    rv = CKR_OK;

cleanup:
    if (blob != NULL)
    {
        azihsm_pkcs11_wipe(blob, masked.len);
        free(blob);
    }
    (void)azihsm_key_delete(key);
    return rv;
}

CK_RV azihsm_pkcs11_key_aes_unmask(
    uint32_t hsm_session,
    const CK_BYTE *blob,
    CK_ULONG blob_len,
    uint32_t *out_key
)
{
    if ((blob == NULL) || (blob_len == 0) || (out_key == NULL))
    {
        return CKR_ARGUMENTS_BAD;
    }
    struct azihsm_buffer masked = { (void *)blob, (uint32_t)blob_len };
    azihsm_handle key = 0;
    azihsm_status st = azihsm_key_unmask(hsm_session, AZIHSM_KEY_KIND_AES, &masked, &key);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("key_unmask failed: %d", (int)st);
        /* The only handle passed here is the device session: it going stale
         * means the recorded login no longer holds. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_USER_NOT_LOGGED_IN);
    }
    *out_key = key;
    return CKR_OK;
}

void azihsm_pkcs11_key_release(uint32_t key_handle)
{
    if (key_handle != 0)
    {
        (void)azihsm_key_delete(key_handle);
    }
}

/* Translate a CBC encrypt/decrypt status. A decrypt with padding surfaces bad
 * PKCS#7 padding as INTERNAL_ERROR (api/lib pkcs7_unpad), which for the caller
 * means the ciphertext is invalid, not a device fault — map that one case to
 * the spec's CKR_ENCRYPTED_DATA_INVALID; everything else takes the shared map,
 * with a stale device key handle reading as CKR_KEY_HANDLE_INVALID. */
static CK_RV cbc_status_to_ckr(azihsm_status st, bool encrypt, bool pad)
{
    if (!encrypt && pad && (st == AZIHSM_STATUS_INTERNAL_ERROR))
    {
        return CKR_ENCRYPTED_DATA_INVALID;
    }
    return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
}

CK_RV azihsm_pkcs11_key_aes_cbc(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    if ((iv == NULL) || (out_len == NULL) || ((in == NULL) && (in_len > 0)))
    {
        return CKR_ARGUMENTS_BAD;
    }

    /* The device chains the evolving IV back into the params struct, so give it
     * a private copy each call: the caller's IV must stay the operation's seed
     * (a sizing pass or too-small retry re-runs with the same IV). */
    struct azihsm_algo_aes_cbc_params params;
    memcpy(params.iv, iv, sizeof(params.iv));
    struct azihsm_algo algo = { pad ? AZIHSM_ALGO_ID_AES_CBC_PAD : AZIHSM_ALGO_ID_AES_CBC,
                                &params,
                                sizeof(params) };
    struct azihsm_buffer inbuf = { (void *)in, (uint32_t)in_len };

    /* The device accepts only an output buffer of EXACTLY the required length
     * (an oversized one fails with BUFFER_TOO_SMALL and no required-length
     * report), while PKCS#11 lets the caller hand any large-enough buffer. So
     * size first, unconditionally, and run the real call at that exact length. */
    struct azihsm_buffer outbuf = { NULL, 0 };
    azihsm_status st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                               : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    if ((st != AZIHSM_STATUS_BUFFER_TOO_SMALL) && (st != AZIHSM_STATUS_SUCCESS))
    {
        AZIHSM_PKCS11_LOG("crypt_%s sizing failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        return cbc_status_to_ckr(st, encrypt, pad);
    }
    CK_ULONG required = outbuf.len;
    if ((out == NULL) || (required == 0))
    {
        /* Pure sizing request, or an operation with no output bytes. */
        *out_len = required;
        return CKR_OK;
    }
    if (*out_len < required)
    {
        *out_len = required;
        return CKR_BUFFER_TOO_SMALL;
    }

    memcpy(params.iv, iv, sizeof(params.iv)); /* the sizing pass advanced it */
    outbuf.ptr = out;
    outbuf.len = (uint32_t)required;
    st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                 : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("crypt_%s failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        return cbc_status_to_ckr(st, encrypt, pad);
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

#else /* !AZIHSM_WITH_HSM ---------------------------------------------------- */

/* No device linked: key material cannot exist, so the key-backed paths report
 * unsupported. Entry-point validation up to the binding stays exercisable. */

CK_RV azihsm_pkcs11_key_aes_generate(
    uint32_t hsm_session,
    uint32_t bit_len,
    CK_BYTE **out_blob,
    CK_ULONG *out_blob_len
)
{
    (void)hsm_session;
    (void)bit_len;
    (void)out_blob;
    (void)out_blob_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_unmask(
    uint32_t hsm_session,
    const CK_BYTE *blob,
    CK_ULONG blob_len,
    uint32_t *out_key
)
{
    (void)hsm_session;
    (void)blob;
    (void)blob_len;
    (void)out_key;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

void azihsm_pkcs11_key_release(uint32_t key_handle)
{
    (void)key_handle;
}

CK_RV azihsm_pkcs11_key_aes_cbc(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)encrypt;
    (void)pad;
    (void)key_handle;
    (void)iv;
    (void)in;
    (void)in_len;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

#endif /* AZIHSM_WITH_HSM */
