// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/*
 * HSM key binding (see azihsm_pkcs11_key.h). Two builds, mirroring azihsm_pkcs11_hsm.c:
 *   - AZIHSM_WITH_HSM: binds azihsm_key_* / azihsm_crypt_* against the device.
 *   - otherwise: stubs, so the framework and the entry-point validation paths
 *     stay testable with no device present.
 */

#include "azihsm_pkcs11_key.h"
#include "azihsm_pkcs11_internal.h"
#include "azihsm_pkcs11_status.h"

#include <stdlib.h>
#include <string.h>

#ifdef AZIHSM_WITH_HSM
#include "azihsm.h" /* generated by cbindgen from api/native during the build */

/* The IV buffer this file copies into the device CBC params must be exactly the
 * width AES_BLOCK_LEN promises to callers of azihsm_pkcs11_key_aes_cbc. */
_Static_assert(
    sizeof(((struct azihsm_algo_aes_cbc_params *)0)->iv) == AES_BLOCK_LEN,
    "device AES-CBC IV width must equal AES_BLOCK_LEN"
);

/* Likewise for the GCM IV and tag and the XTS tweak: the entry point validates
 * caller parameters against these widths and this file copies exactly them. */
_Static_assert(
    sizeof(((struct azihsm_algo_aes_gcm_params *)0)->iv) == AES_GCM_IV_LEN,
    "device AES-GCM IV width must equal AES_GCM_IV_LEN"
);
_Static_assert(
    sizeof(((struct azihsm_algo_aes_gcm_params *)0)->tag) == AES_GCM_TAG_LEN,
    "device AES-GCM tag width must equal AES_GCM_TAG_LEN"
);
_Static_assert(
    sizeof(((struct azihsm_algo_aes_xts_params *)0)->sector_num) == AES_XTS_TWEAK_LEN,
    "device AES-XTS tweak width must equal AES_XTS_TWEAK_LEN"
);

/*
 * Translate the module's kind to the device key kind and its key-generation
 * algorithm. false for a value outside the enum, which the callers refuse
 * rather than quietly treating as plain AES.
 */
static bool device_kind(azihsm_pkcs11_key_kind_t kind, uint32_t *out_kind, uint32_t *out_keygen)
{
    switch (kind)
    {
    case AZIHSM_PKCS11_KIND_AES:
        *out_kind = AZIHSM_KEY_KIND_AES;
        *out_keygen = AZIHSM_ALGO_ID_AES_KEY_GEN;
        return true;
    case AZIHSM_PKCS11_KIND_AES_GCM:
        *out_kind = AZIHSM_KEY_KIND_AES_GCM;
        *out_keygen = AZIHSM_ALGO_ID_AES_GCM_KEY_GEN;
        return true;
    case AZIHSM_PKCS11_KIND_AES_XTS:
        *out_kind = AZIHSM_KEY_KIND_AES_XTS;
        *out_keygen = AZIHSM_ALGO_ID_AES_XTS_KEY_GEN;
        return true;
    default:
        return false;
    }
}

/*
 * Nothing stops a caller from passing one buffer as both pData and
 * pEncryptedData. The native API would then hold an immutable slice over the
 * input and a mutable one over the output while both describe the same bytes,
 * which Rust does not allow, so the input is staged in a private copy whenever
 * the two ranges touch. *staged is NULL when they do not; release it with
 * stage_free.
 */
static CK_RV stage_overlap(
    const CK_BYTE *in,
    CK_ULONG in_len,
    const CK_BYTE *out,
    CK_ULONG out_len,
    CK_BYTE **staged
)
{
    *staged = NULL;
    if ((in_len == 0) || (out == NULL) || (out_len == 0))
    {
        return CKR_OK;
    }
    if (((uintptr_t)in < ((uintptr_t)out + out_len)) && ((uintptr_t)out < ((uintptr_t)in + in_len)))
    {
        CK_BYTE *copy = (CK_BYTE *)malloc(in_len);
        if (copy == NULL)
        {
            return CKR_HOST_MEMORY;
        }
        memcpy(copy, in, in_len);
        *staged = copy;
    }
    return CKR_OK;
}

/* The staged copy held plaintext or ciphertext and does not outlive the call. */
static void stage_free(CK_BYTE *staged, CK_ULONG len)
{
    if (staged != NULL)
    {
        azihsm_pkcs11_wipe(staged, len);
        free(staged);
    }
}

CK_RV azihsm_pkcs11_key_aes_generate(
    uint32_t hsm_session,
    azihsm_pkcs11_key_kind_t kind,
    uint32_t bit_len,
    CK_BYTE **out_blob,
    CK_ULONG *out_blob_len
)
{
    if ((out_blob == NULL) || (out_blob_len == NULL))
    {
        return CKR_ARGUMENTS_BAD;
    }
    *out_blob = NULL;
    *out_blob_len = 0;
    uint32_t dev_kind = 0;
    uint32_t keygen_algo = 0;
    if (!device_kind(kind, &dev_kind, &keygen_algo))
    {
        return CKR_ARGUMENTS_BAD;
    }

    /*
     * SENSITIVE / EXTRACTABLE / LOCAL are deliberately absent: the SDK rejects
     * them as inputs (it sets them itself), which is why the template
     * normaliser in azihsm_pkcs11_template.c strips them before this call. SESSION is
     * always true — device residence is per-session by design here; the masked
     * blob below is what persists. ENCRYPT and DECRYPT are always both set:
     * the SDK refuses an AES, GCM or XTS key with only one of them (see the
     * header note).
     */
    uint32_t class_secret = AZIHSM_KEY_CLASS_SECRET;
    uint8_t yes = 1;
    struct azihsm_key_prop props[] = {
        { AZIHSM_KEY_PROP_ID_CLASS, &class_secret, sizeof(class_secret) },
        { AZIHSM_KEY_PROP_ID_KIND, &dev_kind, sizeof(dev_kind) },
        { AZIHSM_KEY_PROP_ID_BIT_LEN, &bit_len, sizeof(bit_len) },
        { AZIHSM_KEY_PROP_ID_SESSION, &yes, sizeof(yes) },
        { AZIHSM_KEY_PROP_ID_ENCRYPT, &yes, sizeof(yes) },
        { AZIHSM_KEY_PROP_ID_DECRYPT, &yes, sizeof(yes) },
    };
    struct azihsm_key_prop_list prop_list = { props, sizeof(props) / sizeof(props[0]) };
    struct azihsm_algo algo = { keygen_algo, NULL, 0 };

    azihsm_handle key = 0;
    azihsm_status st = azihsm_key_gen(hsm_session, &algo, &prop_list, &key);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("key_gen(kind %u, %u bits) failed: %d", dev_kind, bit_len, (int)st);
        /* The only handle passed here is the device session: it going stale
         * means the recorded login no longer holds. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_USER_NOT_LOGGED_IN);
    }

    /* Read back the masked blob (two-call sizing), then drop the transient
     * device handle — the blob is the durable form of the key. */
    CK_RV rv = CKR_FUNCTION_FAILED;
    CK_BYTE *blob = NULL;
    struct azihsm_key_prop masked = { AZIHSM_KEY_PROP_ID_MASKED_KEY, NULL, 0 };
    st = azihsm_key_get_prop(key, &masked);
    if ((st != AZIHSM_STATUS_BUFFER_TOO_SMALL) || (masked.len == 0))
    {
        AZIHSM_PKCS11_LOG("masked-key sizing failed: %d", (int)st);
        rv = azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
        goto cleanup;
    }
    blob = (CK_BYTE *)malloc(masked.len);
    if (blob == NULL)
    {
        rv = CKR_HOST_MEMORY;
        goto cleanup;
    }
    masked.val = blob;
    st = azihsm_key_get_prop(key, &masked);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("masked-key readback failed: %d", (int)st);
        rv = azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
        goto cleanup;
    }

    *out_blob = blob;
    *out_blob_len = masked.len;
    blob = NULL; /* ownership moved to the caller */
    rv = CKR_OK;

cleanup:
    if (blob != NULL)
    {
        azihsm_pkcs11_wipe(blob, masked.len);
        free(blob);
    }
    (void)azihsm_key_delete(key);
    return rv;
}

CK_RV azihsm_pkcs11_key_aes_unmask(
    uint32_t hsm_session,
    azihsm_pkcs11_key_kind_t kind,
    const CK_BYTE *blob,
    CK_ULONG blob_len,
    uint32_t *out_key
)
{
    /* The device buffer length is 32-bit; a blob beyond it cannot be passed. */
    uint32_t dev_kind = 0;
    uint32_t keygen_algo = 0;
    if ((blob == NULL) || (blob_len == 0) || (blob_len > (CK_ULONG)UINT32_MAX) ||
        (out_key == NULL) || !device_kind(kind, &dev_kind, &keygen_algo))
    {
        return CKR_ARGUMENTS_BAD;
    }
    struct azihsm_buffer masked = { (void *)blob, (uint32_t)blob_len };
    azihsm_handle key = 0;
    azihsm_status st = azihsm_key_unmask(hsm_session, dev_kind, &masked, &key);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("key_unmask failed: %d", (int)st);
        /* The only handle passed here is the device session: it going stale
         * means the recorded login no longer holds. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_USER_NOT_LOGGED_IN);
    }
    *out_key = key;
    return CKR_OK;
}

void azihsm_pkcs11_key_release(uint32_t key_handle)
{
    if (key_handle != 0)
    {
        (void)azihsm_key_delete(key_handle);
    }
}

/* The status map's INTERNAL_ERROR literal must be the SDK's, since the map is
 * compiled without azihsm.h. */
_Static_assert(
    AZIHSM_STATUS_INTERNAL_ERROR == -5,
    "azihsm_pkcs11_status.c assumes INTERNAL_ERROR == -5"
);

CK_RV azihsm_pkcs11_key_aes_cbc(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    /* The device buffer length is 32-bit (the entry point reports an
     * over-long input as a *_LEN_RANGE before it gets here). */
    if ((iv == NULL) || (out_len == NULL) || ((in == NULL) && (in_len > 0)) ||
        (in_len > (CK_ULONG)UINT32_MAX))
    {
        return CKR_ARGUMENTS_BAD;
    }

    /* The device chains the evolving IV back into the params struct, so give it
     * a private copy each call: the caller's IV must stay the operation's seed
     * (a sizing pass or too-small retry re-runs with the same IV). */
    struct azihsm_algo_aes_cbc_params params;
    memcpy(params.iv, iv, sizeof(params.iv));
    struct azihsm_algo algo = { pad ? AZIHSM_ALGO_ID_AES_CBC_PAD : AZIHSM_ALGO_ID_AES_CBC,
                                &params,
                                sizeof(params) };
    struct azihsm_buffer inbuf = { (void *)in, (uint32_t)in_len };

    /* The device accepts only an output buffer of EXACTLY the required length
     * (an oversized one fails with BUFFER_TOO_SMALL and no required-length
     * report), while PKCS#11 lets the caller hand any large-enough buffer. So
     * size first, unconditionally, and run the real call at that exact length. */
    struct azihsm_buffer outbuf = { NULL, 0 };
    azihsm_status st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                               : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    if ((st != AZIHSM_STATUS_BUFFER_TOO_SMALL) && (st != AZIHSM_STATUS_SUCCESS))
    {
        AZIHSM_PKCS11_LOG("crypt_%s sizing failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
    }
    CK_ULONG required = outbuf.len;
    if ((out == NULL) || (required == 0))
    {
        /* Pure sizing request, or an operation with no output bytes. */
        *out_len = required;
        return CKR_OK;
    }
    if (*out_len < required)
    {
        *out_len = required;
        return CKR_BUFFER_TOO_SMALL;
    }

    /* Only the fill call needs overlap staging: the sizing pass above writes
     * nothing. */
    CK_BYTE *staged = NULL;
    CK_RV rv = stage_overlap(in, in_len, out, required, &staged);
    if (rv != CKR_OK)
    {
        return rv;
    }
    if (staged != NULL)
    {
        inbuf.ptr = staged;
    }

    memcpy(params.iv, iv, sizeof(params.iv)); /* the sizing pass advanced it */
    outbuf.ptr = out;
    outbuf.len = (uint32_t)required;
    st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                 : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    stage_free(staged, in_len);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("crypt_%s failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        /* The device may already have written into `out` (a padded decrypt is
         * rejected only after the raw blocks exist); a failed call must not
         * leave that behind a reported length of zero. */
        azihsm_pkcs11_wipe(out, required);
        /* Bad PKCS#7 padding on a padded decrypt reads as invalid ciphertext;
         * see azihsm_pkcs11_ckr_from_cbc_fill. */
        return azihsm_pkcs11_ckr_from_cbc_fill((int)st, !encrypt && pad);
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

CK_RV azihsm_pkcs11_key_aes_gcm(
    bool encrypt,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *aad,
    CK_ULONG aad_len,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *tag,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    if ((iv == NULL) || (tag == NULL) || (out == NULL) || (out_len == NULL) ||
        ((in == NULL) && (in_len > 0)) || ((aad == NULL) && (aad_len > 0)) ||
        (in_len > (CK_ULONG)UINT32_MAX) || (aad_len > (CK_ULONG)UINT32_MAX))
    {
        return CKR_ARGUMENTS_BAD;
    }
    /* GCM output is exactly as long as its input (the tag travels apart), and
     * unlike CBC the device takes any buffer at least that large. */
    if (*out_len < in_len)
    {
        *out_len = in_len;
        return CKR_BUFFER_TOO_SMALL;
    }

    struct azihsm_algo_aes_gcm_params params;
    memcpy(params.iv, iv, sizeof(params.iv));
    if (encrypt)
    {
        memset(params.tag, 0, sizeof(params.tag)); /* the device writes it back */
    }
    else
    {
        memcpy(params.tag, tag, sizeof(params.tag));
    }
    struct azihsm_buffer aadbuf = { (void *)aad, (uint32_t)aad_len };
    params.aad = (aad_len > 0) ? &aadbuf : NULL; /* NULL reads as "no AAD" */
    struct azihsm_algo algo = { AZIHSM_ALGO_ID_AES_GCM, &params, sizeof(params) };
    struct azihsm_buffer inbuf = { (void *)in, (uint32_t)in_len };

    CK_BYTE *staged = NULL;
    CK_RV rv = stage_overlap(in, in_len, out, in_len, &staged);
    if (rv != CKR_OK)
    {
        return rv;
    }
    if (staged != NULL)
    {
        inbuf.ptr = staged;
    }
    struct azihsm_buffer outbuf = { out, (uint32_t)in_len };
    azihsm_status st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                               : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    stage_free(staged, in_len);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("gcm_%s failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        /* A decrypt that fails authentication must not leave unauthenticated
         * plaintext behind, whatever the device wrote before it refused. */
        azihsm_pkcs11_wipe(out, in_len);
        /* A tag mismatch arrives as the generic DDI failure (-8) on every
         * backend today, indistinguishable from a device fault, so it maps to
         * CKR_FUNCTION_FAILED like any other; see azihsm_pkcs11_status.c. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
    }
    if (encrypt)
    {
        memcpy(tag, params.tag, sizeof(params.tag));
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

CK_RV azihsm_pkcs11_key_aes_xts(
    bool encrypt,
    uint32_t key_handle,
    const CK_BYTE *tweak,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    if ((tweak == NULL) || (in == NULL) || (out == NULL) || (out_len == NULL) || (in_len == 0) ||
        (in_len > AES_XTS_MAX_DATA_LEN) || ((in_len % AES_BLOCK_LEN) != 0))
    {
        return CKR_ARGUMENTS_BAD;
    }
    if (*out_len < in_len)
    {
        *out_len = in_len;
        return CKR_BUFFER_TOO_SMALL;
    }

    /* The whole message is one data unit: PKCS#11 carries no data-unit length,
     * so any other split would be a private convention no peer reproduces. */
    struct azihsm_algo_aes_xts_params params;
    memcpy(params.sector_num, tweak, sizeof(params.sector_num));
    params.data_unit_length = (uint32_t)in_len;
    struct azihsm_algo algo = { AZIHSM_ALGO_ID_AES_XTS, &params, sizeof(params) };
    struct azihsm_buffer inbuf = { (void *)in, (uint32_t)in_len };

    CK_BYTE *staged = NULL;
    CK_RV rv = stage_overlap(in, in_len, out, in_len, &staged);
    if (rv != CKR_OK)
    {
        return rv;
    }
    if (staged != NULL)
    {
        inbuf.ptr = staged;
    }
    struct azihsm_buffer outbuf = { out, (uint32_t)in_len };
    azihsm_status st = encrypt ? azihsm_crypt_encrypt(&algo, key_handle, &inbuf, &outbuf)
                               : azihsm_crypt_decrypt(&algo, key_handle, &inbuf, &outbuf);
    stage_free(staged, in_len);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("xts_%s failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        azihsm_pkcs11_wipe(out, in_len);
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

struct azihsm_pkcs11_aes_cbc_stream
{
    bool encrypt;
    bool pad;
    azihsm_handle ctx;                        /* SDK stream context; 0 = none */
    struct azihsm_algo_aes_cbc_params params; /* the context points here (chained IV) */
};

CK_RV azihsm_pkcs11_key_aes_cbc_stream_new(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    azihsm_pkcs11_aes_cbc_stream_t **out
)
{
    if ((iv == NULL) || (out == NULL))
    {
        return CKR_ARGUMENTS_BAD;
    }
    *out = NULL;
    azihsm_pkcs11_aes_cbc_stream_t *stream =
        (azihsm_pkcs11_aes_cbc_stream_t *)calloc(1, sizeof(*stream));
    if (stream == NULL)
    {
        return CKR_HOST_MEMORY;
    }
    stream->encrypt = encrypt;
    stream->pad = pad;
    memcpy(stream->params.iv, iv, sizeof(stream->params.iv));

    /* The context keeps a pointer to stream->params only; the algo descriptor
     * itself is read during the call. */
    struct azihsm_algo algo = { pad ? AZIHSM_ALGO_ID_AES_CBC_PAD : AZIHSM_ALGO_ID_AES_CBC,
                                &stream->params,
                                sizeof(stream->params) };
    azihsm_handle ctx = 0;
    azihsm_status st = encrypt ? azihsm_crypt_encrypt_init(&algo, key_handle, &ctx)
                               : azihsm_crypt_decrypt_init(&algo, key_handle, &ctx);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG("crypt_%s_init failed: %d", encrypt ? "encrypt" : "decrypt", (int)st);
        azihsm_pkcs11_wipe(stream, sizeof(*stream));
        free(stream);
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_KEY_HANDLE_INVALID);
    }
    stream->ctx = ctx;
    *out = stream;
    return CKR_OK;
}

CK_RV azihsm_pkcs11_key_aes_cbc_stream_update(
    azihsm_pkcs11_aes_cbc_stream_t *stream,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    if ((stream == NULL) || (out == NULL) || (out_len == NULL) || ((in == NULL) && (in_len > 0)) ||
        (in_len > AES_CBC_STREAM_MAX_PART))
    {
        return CKR_ARGUMENTS_BAD;
    }
    if (in_len == 0)
    {
        /* An empty part changes nothing in the stream, and the SDK would have
         * to be handed a NULL input buffer for it. */
        *out_len = 0;
        return CKR_OK;
    }
    /* Unlike the one-shot call the stream takes any buffer that is large
     * enough, so the capacity only has to fit the SDK's 32-bit length. */
    uint32_t cap = (*out_len > (CK_ULONG)UINT32_MAX) ? UINT32_MAX : (uint32_t)*out_len;

    CK_BYTE *staged = NULL;
    CK_RV rv = stage_overlap(in, in_len, out, cap, &staged);
    if (rv != CKR_OK)
    {
        return rv;
    }
    struct azihsm_buffer inbuf = { (staged != NULL) ? staged : (void *)in, (uint32_t)in_len };
    struct azihsm_buffer outbuf = { out, cap };
    azihsm_status st = stream->encrypt ? azihsm_crypt_encrypt_update(stream->ctx, &inbuf, &outbuf)
                                       : azihsm_crypt_decrypt_update(stream->ctx, &inbuf, &outbuf);
    stage_free(staged, in_len);
    if (st == AZIHSM_STATUS_BUFFER_TOO_SMALL)
    {
        *out_len = outbuf.len; /* the required length; nothing was consumed */
        return CKR_BUFFER_TOO_SMALL;
    }
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG(
            "crypt_%s_update failed: %d",
            stream->encrypt ? "encrypt" : "decrypt",
            (int)st
        );
        /* The only handle passed is this module's own stream context, so its
         * going stale is an internal fault rather than a caller's bad key. */
        return azihsm_pkcs11_ckr_from_azihsm_hint((int)st, CKR_FUNCTION_FAILED);
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

CK_RV azihsm_pkcs11_key_aes_cbc_stream_final(
    azihsm_pkcs11_aes_cbc_stream_t *stream,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    if ((stream == NULL) || (out == NULL) || (out_len == NULL) ||
        (*out_len < AES_CBC_STREAM_FINAL_MAX))
    {
        return CKR_ARGUMENTS_BAD;
    }
    struct azihsm_buffer outbuf = { out, AES_CBC_STREAM_FINAL_MAX };
    azihsm_status st = stream->encrypt ? azihsm_crypt_encrypt_finish(stream->ctx, &outbuf)
                                       : azihsm_crypt_decrypt_finish(stream->ctx, &outbuf);
    if (st != AZIHSM_STATUS_SUCCESS)
    {
        AZIHSM_PKCS11_LOG(
            "crypt_%s_finish failed: %d",
            stream->encrypt ? "encrypt" : "decrypt",
            (int)st
        );
        /* A padded decrypt writes the raw last block before its padding check
         * can refuse it. */
        azihsm_pkcs11_wipe(out, AES_CBC_STREAM_FINAL_MAX);
        return azihsm_pkcs11_ckr_from_cbc_fill((int)st, !stream->encrypt && stream->pad);
    }
    *out_len = outbuf.len;
    return CKR_OK;
}

void azihsm_pkcs11_key_aes_cbc_stream_free(azihsm_pkcs11_aes_cbc_stream_t *stream)
{
    if (stream == NULL)
    {
        return;
    }
    if (stream->ctx != 0)
    {
        (void)azihsm_free_ctx_handle(stream->ctx); /* before the params it points at */
    }
    azihsm_pkcs11_wipe(stream, sizeof(*stream));
    free(stream);
}

#else /* !AZIHSM_WITH_HSM ---------------------------------------------------- */

/* No device linked: key material cannot exist, so the key-backed paths report
 * unsupported. Entry-point validation up to the binding stays exercisable. */

CK_RV azihsm_pkcs11_key_aes_generate(
    uint32_t hsm_session,
    azihsm_pkcs11_key_kind_t kind,
    uint32_t bit_len,
    CK_BYTE **out_blob,
    CK_ULONG *out_blob_len
)
{
    (void)hsm_session;
    (void)kind;
    (void)bit_len;
    (void)out_blob;
    (void)out_blob_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_unmask(
    uint32_t hsm_session,
    azihsm_pkcs11_key_kind_t kind,
    const CK_BYTE *blob,
    CK_ULONG blob_len,
    uint32_t *out_key
)
{
    (void)hsm_session;
    (void)kind;
    (void)blob;
    (void)blob_len;
    (void)out_key;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

void azihsm_pkcs11_key_release(uint32_t key_handle)
{
    (void)key_handle;
}

CK_RV azihsm_pkcs11_key_aes_cbc(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)encrypt;
    (void)pad;
    (void)key_handle;
    (void)iv;
    (void)in;
    (void)in_len;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_gcm(
    bool encrypt,
    uint32_t key_handle,
    const CK_BYTE *iv,
    const CK_BYTE *aad,
    CK_ULONG aad_len,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *tag,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)encrypt;
    (void)key_handle;
    (void)iv;
    (void)aad;
    (void)aad_len;
    (void)in;
    (void)in_len;
    (void)tag;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_xts(
    bool encrypt,
    uint32_t key_handle,
    const CK_BYTE *tweak,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)encrypt;
    (void)key_handle;
    (void)tweak;
    (void)in;
    (void)in_len;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_cbc_stream_new(
    bool encrypt,
    bool pad,
    uint32_t key_handle,
    const CK_BYTE *iv,
    azihsm_pkcs11_aes_cbc_stream_t **out
)
{
    (void)encrypt;
    (void)pad;
    (void)key_handle;
    (void)iv;
    (void)out;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_cbc_stream_update(
    azihsm_pkcs11_aes_cbc_stream_t *stream,
    const CK_BYTE *in,
    CK_ULONG in_len,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)stream;
    (void)in;
    (void)in_len;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

CK_RV azihsm_pkcs11_key_aes_cbc_stream_final(
    azihsm_pkcs11_aes_cbc_stream_t *stream,
    CK_BYTE *out,
    CK_ULONG *out_len
)
{
    (void)stream;
    (void)out;
    (void)out_len;
    return CKR_FUNCTION_NOT_SUPPORTED;
}

void azihsm_pkcs11_key_aes_cbc_stream_free(azihsm_pkcs11_aes_cbc_stream_t *stream)
{
    (void)stream; /* no stream can exist without a device */
}

#endif /* AZIHSM_WITH_HSM */
