#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
"""
Generate src/p11_stubs.c — the PKCS#11 functions the module does not implement
yet — from the canonical v3.1 function signatures.

The signatures are captured in tools/pkcs11f_signatures.tsv (name<TAB>arglist),
parsed once from the OASIS pkcs11f.h. Regenerate that TSV with:

    python3 - <<'PY' > tools/pkcs11f_signatures.tsv
    import re
    txt = open("include/pkcs11-v3.1/pkcs11f.h").read()
    txt = re.sub(r"/\\*.*?\\*/", "", txt, flags=re.S)          # strip comments
    txt = txt.replace("#ifdef CK_NEED_ARG_LIST", "").replace("#endif", "")
    for m in re.finditer(r"CK_PKCS11_FUNCTION_INFO\\((C_\\w+)\\)\\s*\\(([^;]*)\\)\\s*;", txt, re.S):
        args = re.sub(r"\\s+", " ", m.group(2)).strip() or "void"
        print(f"{m.group(1)}\\t{args}")
    PY

Then: python3 tools/gen_stubs.py > src/p11_stubs.c
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TSV = os.path.join(HERE, "pkcs11f_signatures.tsv")

# Functions implemented in dedicated translation units (NOT stubbed here).
IMPLEMENTED = {
    "C_Initialize", "C_Finalize", "C_GetInfo",
    "C_GetFunctionList", "C_GetInterfaceList", "C_GetInterface",
    "C_GetSlotList", "C_GetSlotInfo", "C_GetTokenInfo",
    "C_GetMechanismList", "C_GetMechanismInfo", "C_WaitForSlotEvent",
    "C_OpenSession", "C_CloseSession", "C_CloseAllSessions",
    "C_GetSessionInfo", "C_Login", "C_Logout",
    "C_CreateObject", "C_DestroyObject", "C_FindObjectsInit",
    "C_FindObjects", "C_FindObjectsFinal", "C_GetAttributeValue",
    "C_DigestInit", "C_Digest", "C_DigestUpdate", "C_DigestFinal",
}
# Legacy parallel-function calls return CKR_FUNCTION_NOT_PARALLEL per the spec.
NOT_PARALLEL = {"C_GetFunctionStatus", "C_CancelFunction"}

HEADER = """// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/*
 * GENERATED by tools/gen_stubs.py — do not edit by hand.
 *
 * Every PKCS#11 entry point not implemented in a dedicated translation unit is
 * defined here as a real symbol returning CKR_FUNCTION_NOT_SUPPORTED (or
 * CKR_FUNCTION_NOT_PARALLEL for the two legacy parallel-execution calls), so the
 * module always exposes a complete CK_FUNCTION_LIST / _3_0.
 */

#include "p11_internal.h"
"""


def main():
    sigs = [l.rstrip("\n").split("\t") for l in open(TSV) if l.strip()]
    out = [HEADER]
    for name, args in sigs:
        if name in IMPLEMENTED:
            continue
        rv = "CKR_FUNCTION_NOT_PARALLEL" if name in NOT_PARALLEL \
            else "CKR_FUNCTION_NOT_SUPPORTED"
        body = [f"\nCK_RV {name}({args})", "{"]
        if args != "void":
            for a in args.split(","):
                var = a.strip().split()[-1].lstrip("*")
                body.append(f"    (void){var};")
        body.append(f"    return {rv};")
        body.append("}")
        out.append("\n".join(body))
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
