// Copyright (C) Microsoft Corporation. All rights reserved.

//! Module for Cryptographic Key Handles.

use crate::crypto::aes::AesKey;
use crate::crypto::ecc::EccPrivateKey;
use crate::crypto::ecc::EccPublicKey;
use crate::crypto::hmac::HmacKey;
use crate::crypto::rsa::RsaPrivateKey;
use crate::crypto::rsa::RsaPublicKey;
use crate::crypto::secret::SecretKey;
use crate::function::ApiRev;

/// Enumeration for storing Cryptographic Key Handles.
#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone)]
pub(crate) enum Key {
    /// RSA Private Key.
    RsaPrivate(RsaPrivateKey),

    /// RSA Public Key.
    #[allow(unused)]
    RsaPublic(RsaPublicKey),

    /// ECC Private Key.
    EccPrivate(EccPrivateKey),

    /// ECC Public Key.
    #[allow(unused)]
    EccPublic(EccPublicKey),

    /// AES Key.
    Aes(AesKey),

    /// Bits generated by key exchange.
    Secret(SecretKey),

    /// Session
    Session(ApiRev),

    /// Hmac
    Hmac(HmacKey),
}
