name: Create New Cache

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/create_new_cache.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  create_new_cache_ubuntu:

    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Run Setup
      run: cargo xtask precheck --setup
    - name: Save Cargo cache
      uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ github.sha }}

  create_new_cache_windows:

    runs-on: windows-2025-vs2026

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Run Setup
      run: cargo xtask precheck --setup
    - name: Save Cargo cache
      uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ github.sha }}
