name: Test
 
on:
  push:
    branches: [main, dev, fw-main]
  pull_request:
    branches: [main, dev, fw-main]
  merge_group:
    branches: [main, dev, fw-main]
  workflow_dispatch:
 
jobs:
  simple_ubuntu:
    env:
      JOB_ID: build_ubuntu-azihsm-arm64-ubuntu2404-image-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    runs-on: [azihsm-arm64-gh-pool-westus2-New]
    steps:
      - name: echo
        run: echo "Hello world, Updated change to kick off build"
