// Copyright (C) Microsoft Corporation. All rights reserved.

//! OpenSSL-based random number generation implementation for Linux systems.
//!
//! This module provides a cryptographically secure random number generator (CSPRNG)
//! using OpenSSL's `RAND_bytes` function. This implementation is specifically designed
//! for Linux platforms and provides high-quality entropy suitable for cryptographic
//! operations.
//!
//! The implementation leverages OpenSSL's battle-tested random number generation
//! capabilities, which automatically seed from the system's entropy sources and
//! provide cryptographically strong random numbers.
//!
//! # Platform Support
//!
//! This module is only available on Linux systems. For Windows systems, see the
//! `rand_cng` module which provides similar functionality using Windows Cryptography
//! API: Next Generation (CNG).

use openssl::rand;

use super::*;

/// OpenSSL-based random number generator implementation.
///
/// This struct provides a cryptographically secure random number generator using
/// OpenSSL's `RAND_bytes` function. The implementation is stateless and can be
/// cloned safely, as the actual entropy generation is handled by OpenSSL's
/// internal PRNG state.
///
/// # Security Considerations
///
/// - Uses OpenSSL's cryptographically secure PRNG
/// - Automatically handles seeding from system entropy sources
/// - Suitable for generating keys, nonces, and other cryptographic material
/// - Thread-safe (OpenSSL handles internal locking)
///
/// # Performance
///
/// The performance characteristics depend on the underlying OpenSSL implementation
/// and system entropy sources. Generally provides excellent performance for
/// most cryptographic use cases.
#[derive(Debug, Clone)]
pub struct OsslRng;

impl RngOp for OsslRng {
    /// Generates cryptographically secure random bytes using OpenSSL.
    ///
    /// This method fills the provided buffer with cryptographically strong
    /// random bytes using OpenSSL's `RAND_bytes` function. The function is
    /// suitable for generating cryptographic keys, initialization vectors,
    /// nonces, and other security-critical random values.
    ///
    /// # Arguments
    ///
    /// * `buf` - A mutable byte slice that will be filled with random data.
    ///
    /// # Returns
    ///
    /// * `Ok(())` - If random byte generation was successful
    /// * `Err(CryptoError::RngError)` - If OpenSSL's random number generation
    ///   fails for any reason (e.g., insufficient entropy, system error)
    ///
    /// # Errors
    ///
    /// This function will return a `CryptoError::RngError` if:
    /// - The OpenSSL PRNG is not properly seeded
    /// - A system-level error occurs during entropy gathering
    /// - OpenSSL encounters an internal error
    ///
    /// # Security Notes
    ///
    /// - The generated bytes are cryptographically secure and suitable for
    ///   any cryptographic purpose
    /// - The function does not leak timing information about the generated
    ///   random values
    /// - The underlying OpenSSL implementation handles proper entropy mixing
    ///   and periodic reseeding
    fn rand_bytes(buf: &mut [u8]) -> Result<(), CryptoError> {
        rand::rand_bytes(buf).map_err(|_| CryptoError::RngError)
    }
}
